name: EconomyAPI
author: WatsonLLC
description: Economy API development
version: 0.0.1
api-version: 1.19
main: com.watsonllc.economyapi.Economy
commands:
  balance:
  createaccount:
  setbalance: